### ISSUE TITLE
请问一下，为啥报这个错误

### ISSUE THREAD

**Issue by qllqll** [xiaozhu188/game-match3#1]
![image](https://github.com/xiaozhu188/game-match3/assets/11662465/f51a9bb7-2e0a-498b-b3e1-8f77a3c9ce76)

**Comment by xiaozhu188** [comment]
在assets-manifest.json中，"name":["preload/cauldron-skeleton.atlas"]改为”name“:"preload/cauldron-skeleton.atlas"。还有一个"name": "common/dragon-skeleton.atlas"也需要改。

**Comment by xiaozhu188** [comment]
在assets-manifest.json中，"name":["preload/cauldron-skeleton.atlas"]改为”name“:"preload/cauldron-skeleton.atlas"。还有一个"name": "common/dragon-skeleton.atlas"也需要改。
